<?php

namespace Universal\UniversalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * statutsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutsRepository extends EntityRepository
{
}
